### ISSUE TITLE
education appliction

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#101]
pls. edit the metric with the veteran quote--can we take the "barney" part out--that seems kind of offensive after reviewing.  so it would just be "It's really simple...Military people love that. They love that."  if we use the ellipsis it's still accurate.

  also there's a weird character thing happening with  a "tm".

![screen shot 2016-10-14 at 8 40 44 pm](https://cloud.githubusercontent.com/assets/13770771/19406140/a5d5cdf2-924e-11e6-8140-91f9be6a4e4d.png)

**Comment by koconnor719** [comment]
@robertfairhead hi bob we are demoing this to VA leadership and widely distributing the URL--do you know when this error above can be fixed pls:)

**Comment by robertfairhead** [comment]
Looks like it's a Safari only issue where it thinks it's Latin-1 versus UTF-8 encoding. I'll add a meta tag that should sort it out and remove the barney part
