### ISSUE TITLE
Add new forms to scorecard

### ISSUE THREAD

**Issue by robertfairhead** [department-of-veterans-affairs/vets.gov-status#174]
@leannammiller Can you details on what needs to be added?

**Comment by leannammiller** [comment]
not sure what baseline analytics we have access to yet. here's the next set of forms: https://github.com/department-of-veterans-affairs/edu-benefits-team/blob/master/family-of-forms/form-usage-stats.md

**Comment by robertfairhead** [comment]
Should this be own it's stand-alone card on the main list at https://www.vets.gov/scorecard/? Or would this just be more details for https://www.vets.gov/scorecard/boards/eduapply.html?

It feels to me more like the latter in that this is an expansion of the existing education application, but wanted to check if that's the direction.

**Comment by leannammiller** [comment]
more details for education.

**Comment by robertfairhead** [comment]
got it. once we clear out the account stuff from dev, we'll get something up for you to look at and then get kelly's approval to push to prod

**Comment by robertfairhead** [comment]
Deployed these to prod after Josh Q approval
