### ISSUE TITLE
Collect info for blue button scorecard

### ISSUE THREAD

**Issue by robertfairhead** [department-of-veterans-affairs/vets.gov-status#175]

**Comment by robertfairhead** [comment]
@mikeusdsva the initial empty board can be seen at https://dev.vets.gov/scorecard/boards/healthrecords.html

It's on the demo branch. You're welcome to edit it there or put comments here and we make the updates.

**Comment by leannammiller** [comment]
remember to update this when we launch.

**Comment by robertfairhead** [comment]
On https://staging.vets.gov/scorecard/ there's a non-functional "coming soon" card for it under "Manage"

There's a blank board for it at https://staging.vets.gov/scorecard/boards/healthrecords.html which we can update with what ever you like.

**Comment by robertfairhead** [comment]
I'm going to close this here. @leannammiller when you're ready for this to be worked with actual data we'll open a ticket in vets.gov-team with label Nebula so it can be included in our sprint there /cc @rroueche

**Comment by leannammiller** [comment]
I'll just use this ticket to track the communication around the language and what data should be used. 

Tile should say: 

Health Records

Veterans can view and download their electronic health records

**Comment by robertfairhead** [comment]
I updated per above on staging: https://staging.vets.gov/scorecard/

Will push that update today.

Once I do, I'll close this ticket. I'll open a new one on vets.gov-team to track this (in ice-box for now). That way we can track for our Nebula sprint-planning.
