### ISSUE TITLE
Import va_common styles

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#19]
We should probably do this sooner rather than later, as I'm reticent to spend much time on styling without these in place. Unless there's a vets.gov practice of which I am unaware.

**Comment by cmgiven** [comment]
@robertfairhead: Do you have a reaction here? Is this a logical next step?

**Comment by robertfairhead** [comment]
i think @bshyong @crwallace @melwoodard were working on some standard vets.gov styling. Is there something that @cmgiven can pull in? he's helping us out with creating an HTML dashboard/scorecard for the project for a few days.

I agree that it's not worth doing much on the styling side if there's already a common vets.gov package that exists.

**Comment by robertfairhead** [comment]
@cmgiven not sure how much time you'll have today, but i'd say go ahead and import va_common styles if you want to do any styling work, given our frontend team is pretty busy now. if we need to tweak later for vets.gov purposes, we can.

**Comment by robertfairhead** [comment]
Redesign completed
