### ISSUE TITLE
Jenkins deploys failing

### ISSUE THREAD

**Issue by robertfairhead** [department-of-veterans-affairs/vets.gov-status#219]
@knkski the jenkins deploys seem to be failing due to a permissions issue with the S3 bucket (as best I can make out).

http://jenkins.vetsgov-internal/blue/organizations/jenkins/department-of-veterans-affairs%2Fvets.gov-status/detail/master/3/pipeline/

Shell output:

[airs_vets.gov-status_master-LZ6I6ORRVOTLYDL4YRGQCJBCKPGFP37VV4LFUJSHI57D6SJGODZQ] Running shell script
+ bash --login -c 'aws s3 sync --acl public-read --delete --region us-gov-west-1 _site s3://dsva-vetsgov-scorecard-dev/'
fatal error: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
script returned exit code 1

I updated the Jenkinsfile to skip deploys on PRs which got http://jenkins.vetsgov-internal/blue/organizations/jenkins/department-of-veterans-affairs%2Fvets.gov-status/detail/2017-02-20-ga-data/3/pipeline passing. But when the merge completed the deploy still failed off master, so I think the Jenkinsfile update is unrelated.

Deploys were working when we first tested Jenkins so not sure what happened.

**Comment by knkski** [comment]
This should now be fixed
