### ISSUE TITLE
Is it a Scorecard or Dashboard?

### ISSUE THREAD

**Issue by charwo** [department-of-veterans-affairs/vets.gov-status#251]
Recommend editing the headline to read "Scorecard" to be consistent with URL. 
![image](https://cloud.githubusercontent.com/assets/25183989/23964309/73c82964-098a-11e7-9bc0-e3bc0e6137cd.png)

**Comment by robertfairhead** [comment]
fair point. i think we settled on scorecard as the name after the initial back and forth.

![screen shot 2017-03-16 at 11 10 20 am](https://cloud.githubusercontent.com/assets/6646098/24003239/52ac05ca-0a39-11e7-9100-39e2d4b75d18.png)

@koconnor719 are you ok with the change above?

**Comment by koconnor719** [comment]
yes! sounds good to me.
