### ISSUE TITLE
Add board for "cloud"

### ISSUE THREAD

**Issue by robertfairhead** [department-of-veterans-affairs/vets.gov-status#288]
- let’s add a “cloud” card to our scorecard.  i talked to shawn—thinking metrics would be:  $$, performance, deployment time speed
- goal on $$ is to have a metric we don’t have to constantly update

**Comment by robertfairhead** [comment]
@koconnor719 Which category (Discover, Apply, Track, Manage) do you want the cloud board under? Or do you want it's own section for it like user research?

**Comment by koconnor719** [comment]
hmmmm.  it's not really any of them...what do you think?  maybe "manage" but that's just random:)

**Comment by koconnor719** [comment]
it could be one of the 6 boxes on top (that's not flippable?) if we had 1 metric?  or maybe we could squeeze 2 metrics?  i think that would be ideal.  we could replace healthcare one (since that's kind of apples/oranges since it's product specific and others are cross - cutting...

thoughts? @robertfairhead

**Comment by robertfairhead** [comment]
yep, we can do that @dsh32va can you reach out to shawn (shawn.arnwine@va.gov) to get a metric or two on the cloud transition to use?

**Comment by robertfairhead** [comment]
Met with Shawn yesterday.

No simple metric for cost savings b/c vets.gov costs entwined with appeals. Shawn will look to see what can come up with.

Process underway to import operation metrics (e.g,. up time) to show performance and operational benefits of cloud. Expect initial demo of metrics in 1-2 weeks.

**Comment by koconnor719** [comment]
let's just combine vets.gov and appeals...thanks for digging into this bob.  i don't understand how cloud isn't significant cost savings given what VA is paying for Austin, Terremark (i'm assuming very high given it's a FISMA High cloud env, and Azure ($500M) and CSRA cloud broker $83M...?  given general industry research data isn't cloud exponentially cheaper than gov operating it's own facility?  for the VA comparison are you using a baseline that includes ALL Veteran facing services ?  sorry this just doesn't align w/ how marina has described our business case for going to AWS.  let me know what i'm missing here:) not urgent...

**Comment by robertfairhead** [comment]
@koconnor719 per shawn, the incremental cost per VM for us is relatively low given the VA is already footing all the overhead of running their overall facility. 

The cost per VM to us (vets.gov) was about $2k from the VA. We have about 120 instances. So cost per year is about $240k versus our $200k budget for AWS. For us, going with VA would have about 20% more expensive.

Those figures are not inclusive of labor, facility overhead, etc. that the VA is already paying separately. Just the marginal cost to our project. Shawn was going to see if he could come up with a better cost estimate for those items (for example labor estimated at $98k per year but unclear how many VMs that would cover).

Per his convo with @dsh32va Shawn didn't feel like he had anything more solid to offer on a total cost basis. Dan can chime in if i didn't get that exactly right but that's the gist i took away from the summary.

@koconnor719 if you and shawn come to agreement on a cost savings figure to use, just let us know here and we can easily add it. Otherwise, the only figure we have is the $240k versus $200k number, which we are happy to use if you want.

**Comment by koconnor719** [comment]
Ok thx



Sent with Good (www.good.com)


-----Original Message-----

**Comment by robertfairhead** [comment]
Initial version on https://staging.vets.gov/scorecard/ now. I'll update data and deploy to production this afternoon. Once it's live, we'll close out this ticket. Any new tickets for further updates should be opened on vets.gov-team to allow for Nebula sprint planning going forward.
