### ISSUE TITLE
Display deployments, reachability, error rate metrics

### ISSUE THREAD

**Issue by jkassemi** [department-of-veterans-affairs/vets.gov-status#305]
https://github.com/department-of-veterans-affairs/vets.gov-status/pull/291 collects information on the number of deployments, reachability, and error rate from our monitoring system.

Now we need to figure out where and how we display this information. Do we separate them? Do we highlight any on the index page? Are there any additional metrics we'd like to include?

**Comment by robertfairhead** [comment]
Initial version on https://staging.vets.gov/scorecard/ now. I'll update data and deploy to production this afternoon. Once it's live, we'll close out this ticket. Any new tickets for further updates should be opened on vets.gov-team to allow for Nebula sprint planning going forward.
