### ISSUE TITLE
Implement a last updated date on the page

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3196]
- This will be at a page level
- This will be most recent date across all widgets/components on the page
- Date format: Month day, year
- Schedule the update data job at 00:30 hours daily ([add cron job trigger to groovy file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/seed_job.groovy))
![vagov-dashboard-3112020](https://user-images.githubusercontent.com/2493271/76761528-f354cc00-6765-11ea-804a-92d78ba28867.jpg)
![VAGov-Dashboard-Mobile-3112020](https://user-images.githubusercontent.com/2493271/76761532-f64fbc80-6765-11ea-9b58-85c553c70b9d.jpg)

**Comment by rumyeahs** [comment]
The branch to be merged
Adding smoke tests

**Comment by marisahoenig** [comment]
We added a smoke test. Reassigning to @karlbrown-va to get the [PR](https://github.com/department-of-veterans-affairs/devops/pull/6526) merged for setting up the daily cron job.

**Comment by marisahoenig** [comment]
@katieho-va @marisahoenig Need to add html comment with the time updated for debugging purposes (to be done tomorrow morning)

**Comment by karlbrown-va** [comment]
Jeremy made updates on the PR, should be merged soon. I think we can close this out otherwise.

**Comment by karlbrown-va** [comment]
Also to fix: UI test so it doesn't fail late at night (timezone check)

**Comment by katieho-va** [comment]
UI test fixed and html comment added for time in 12 hour format. Good for review

**Comment by everthoughtworks** [comment]
verified, UI tests fixed using regex.
