### ISSUE TITLE
Implement VA.gov at a glance - Successful transactions - Simple UI

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3197]
**User Story or Problem Statement**
When a user visits the VA.gov at a glance section on the performance dashboard, I want to display the transactions events metrics on the portal so I can present the current statistics on the number of self serve applications filed by veterans and beneficiaries.

**Goal**

A user visiting the VA.gov at a glance section will see the number of form submissions and other transactions on the website by the veterans displayed as a time series plot.

**Tasks**

- Filter for Event Category = Transactions and Page begins with www.va.gov/
- Filter for user segments where LOA levels is 1 or 3
- This should provide the list of all Transactions on va.gov - This is a proxy to successful form submissions and other successful transactions completed on va.gov portal
- Display the transactions data as a time series plot with monthly totals and labels.

**Acceptance Criteria**

- Extract the count of successful transactions, as per the above filter conditions, over the last 12 months
- The data will consist of a count of successful transactions, each with a distinct date stamp 
- Display data graphically

#3206 will follow for additional UI changes to conform to the current designs

**Comment by everthoughtworks** [comment]
x axis does not show in mobile view

**Comment by everthoughtworks** [comment]
<img width="486" alt="Screen Shot 2020-03-18 at 2 18 54 PM" src="https://user-images.githubusercontent.com/58002167/76993731-b33b4800-6923-11ea-8079-e710d7c770cc.png">

**Comment by shefalinayak** [comment]
axis labels should be fixed as of `ee411aa`
