### ISSUE TITLE
Implement Introductory (North star narrative) section on Dashboard

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3201]
**As a** member of the Office of the CTO
**I want to** present a well structured introduction on the Dashboard page 
**so that** any visitor to the dashboard gets an understanding of the goals of the Office of the CTO and how the metrics are tracking towards them

Tasks:
- Build an introduction section on the Dashboard page
- Conform to the design guidelines as illustrated here https://design.va.gov/design/
- UI should be responsive

**Acceptance Criteria**
**Given** any user 
**When** he/she visits the dashboard
**Then** the visitor sees a title VA.gov/Performance Dashboard on the page

**Given** any user 
**When** he/she visits the dashboard
**Then** the visitor sees introductory text on the top of the page (Refer design)

**Dummy Introductory text**
The Office of the CTO at the VA is committed to 
- Optimizing the various tools to improve veteran self service reach and capabilities 
- Make decisions and benefits available to the veterans more quickly
- Improving customer experience - up 9% since launch

**Designs**
![vagov-dashboard-3112020](https://user-images.githubusercontent.com/2493271/76524873-326ede80-6441-11ea-933c-836c1a32011c.jpg)
![VAGov-Dashboard-Mobile-3112020](https://user-images.githubusercontent.com/2493271/76524890-38fd5600-6441-11ea-8d25-ccdeb4d87b3f.jpg)

**Comment by marisahoenig** [comment]
Used verbiage from Todd:
VA.gov was created to provide a single unified digital experience for all Veterans. This performance dashboard tracks our progress in that mission by sharing metrics related to our three North Star goals: 1) increasing the use of self-service tools, measured by the number of logged-in users on VA.gov, 2) decreasing the time Veterans spend waiting for an outcome, measured by successful transactions on VA.gov and 3) consistently delivering a satisfying, reliable, and secure experience, measured by customer satisfaction.

**Comment by marisahoenig** [comment]
Need to make a few changes on Monday

- Implement h1 (North Star), h2(Performance Dashboard, VA @), h3 (accordion)
- North Star: make it an ordered list. put in <p> tag
- Fix screen sizing errors: North Star disappears, Last updated & date in 2 separate spans

**Comment by everthoughtworks** [comment]
North star not visible on mobile devices(ios/android) @marisahoenig

**Comment by marisahoenig** [comment]
@everthoughtworks Fixed in most recent commit. No longer disappears!
