### ISSUE TITLE
Implement tool level 'Transactions' metrics for Education, Disability, Burials & Pension, Profile & Records related top-used tools

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3202]
**As a** member of the Office of the CTO
**I want to** present a count of all the user activities on the various VA.gov tools 
**so that** any visitor to the dashboard gets an insight into the vast userbase of VA and the frequently used services 

Tasks:
* Display the count of user transactions on the specific tools, for the last 30 days, across the various Service line tiles, as illustrated below

**##Service Tile: Education**
 Tool | Page Path filter| Event Category Filter | Event Action Filter
-- | -- | -- | -- 
GI   Bill® Comparison Tool |  regex:/gi-bill-comparison-tool | regex: "Transactions" | N/A
Apply for education benefits  | regex:/application/1990/ | regex: "Transactions" | N/A
Apply to use transferred   education benefits  | regex:/application/1990e/ | regex: "Transactions" | N/A
Manage education   benefits  | regex:/application/1995/ | regex: "Transactions" | N/A
Apply for VET TEC | regex:/apply-for-vettec-form-22-0994 | regex: "Transactions" | N/A
Apply for education benefits   as an eligible dependent  | regex:/application/5490/ | regex: "Transactions" | N/A
Manage education benefits as   an eligible dependent |  regex:/application/5495/ | regex: "Transactions" | N/A
Apply for education benefits under the NCS program | regex:/application/1990n/ | regex: "Transactions" | N/A
GI Bill® School Feedback Tool |  regex:/education/submit-school-feedback | regex: "Transactions" | N/A
Check Post 9/11 GI Bill   benefits  | regex:/education/gi-bill/ | regex: "Transactions" | N/A

**##Service Tile: Disability**
 Tool | Page Path filter| Event Category Filter | Event Action Filter
-- | -- | -- | -- 
File   for disability compensation  | regex:/file-disability-claim-form-21-526ez/ | regex: "Transactions" | N/A
View VA disability ratings | regex:/view-disability-rating/ | regex: "Transactions" | N/A
Check VA claim or appeal status | regex: www.va.gov/track-claims/ | regex: "Transactions" | N/A

**##Service Tile: Burials and Memorials**
 Tool | Page Path filter| Event Category Filter | Event Action Filter
-- | -- | -- | -- 
Apply for pre-need eligibility determination|  regex:/pre-need/form-10007 | regex: "Transactions" | N/A
Apply for burial benefits  | regex:/application/530/ | regex: "Transactions" | N/A

**##Service Tile: Pension**
 Tool | Page Path filter| Event Category Filter | Event Action Filter
-- | -- | -- | -- 
Apply for Veterans Pension benefits  | regex:/application/527ez/ | regex: "Transactions" | N/A

**##Service Tile: Profile & Records**
 Tool | Page Path filter| Event Category Filter | Event Action Filter
-- | -- | -- | -- 
Update contact information & preferences  | regex: www.va.gov/profile/ | regex: "Transactions" | regex: EXCLUDE "direct-deposit-information"
Update direct deposit information  | regex: www.va.gov/profile/ | regex: "Transactions" | regex: "direct-deposit-information"
Download VA benefits letters  | regex: /download-va-letters | regex: "Transactions" | N/A

**Acceptance Criteria**
**Given** any user 
**When** he/she visits the dashboard
**Then** the visitor sees the service line tiles on the page following the VA.gov at a glance section

**Given** any user 
**When** he/she visits the Service Line sections
**Then** the visitor sees the corresponding tools against a total count of Transactions (Total Events within GA) as illustrated in the table above (refer design)

**Given** the daily data update job is run
**When**there is an error updating the chart value
**Then** 
        Exit with error code = 1
        Do not refresh the data on the chart and retain the old values
        Do not update the last updated date

**Comment by marisahoenig** [comment]
Last task is to sort the Transactions per tile in descending order, which is in a new card: https://github.com/department-of-veterans-affairs/vets.gov-status/issues/3241

Moving this one to review.
