### ISSUE TITLE
Implement VA at a glance - Logged in users

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3203]
**As a** member of the Office of the CTO
**I want to** present a count of all the logged in users to the various VA.gov tools 
**so that** any visitor to the dashboard gets an insight into the vast userbase of VA

Tasks:
- Pull data that has the total number of all logged in users across the various VA.gov pages for the last 12 months
- This will be a rolling window for the last 12 calendar months
- Display the count of all logged in users from the last time interval in bold to the left of the chart (Refer design)
- Users that fall within LOA Levels 1 and 3 are considered Logged in (refer GA filter settings below)
- Plot a line chart for the monthly totals for logged in users, for each of the last 12 calendar months (refer design)
- Implement switching between the Logged in users tab and Successful transactions tab. The default tab when the user comes to this page will be the Logged In users tab 
- Desired to have the chart 508 compliant

**Acceptance Criteria**
**Given** any user 
**When** he/she visits the dashboard
**Then** the visitor sees the section 'VA.gov at a glance' on the page

**Given** any user 
**When** he/she visits the dashboard
**Then** the visitor sees Logged in users metrics (Refer design)

**Given**
**When** there is an error updating the chart value
**Then**
Exit with error code = 1
Do not refresh the data on the chart and retain the old values

**Design**
![vagov-dashboard-3112020](https://user-images.githubusercontent.com/2493271/76587536-a00b2100-64ba-11ea-9716-84eb7e06ad54.jpg)
![VAGov-Dashboard-Mobile-3112020](https://user-images.githubusercontent.com/2493271/76587540-a3061180-64ba-11ea-8b2a-e23be004e586.jpg)

**GA 360 Filter settings**
![image](https://user-images.githubusercontent.com/2493271/76588589-c1214100-64bd-11ea-9ea5-90c7574f97f5.png)

**Comment by rumyeahs** [comment]
Chart description text (specifically for screen readers)

This chart displays the total number of logged in users to the various VA services over the last 12 months (from **<start date>** to **<end date>**)
<Month 1>: <Data Value 1>,
<Month 2>: <Data Value 2>,
<Month 3>: <Data Value 3>,
<Month 4>: <Data Value 4>,
<Month 5>: <Data Value 5>,
<Month 6>: <Data Value 6>,
<Month 7>: <Data Value 7>,
<Month 8>: <Data Value 8>,
<Month 9>: <Data Value 9>,
<Month 10>: <Data Value 10>,
<Month 11>: <Data Value 11>,
<Month 12>: <Data Value 12>

**Comment by philherbert** [comment]
An example of a keyboard/screenreader-accessible tabbed interface

https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-2/tabs.html
