### ISSUE TITLE
Add an example VA accordion

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/vets.gov-status#3205]
Add an accordion to the site that looks and behaves exactly like [a bona fide official VA accordion](https://design.va.gov/components/accordions).

**Tech notes**

We should include the VA styles and javascript ([`formation`](https://www.npmjs.com/package/@department-of-veterans-affairs/formation)) using one of these options:

1. (Preferred) Use npm to install the `formation` dependency, and use `webpack` to bundle the assets before the Jekyll build. See [Using Webpack [and React] with Jekyll](https://medium.com/@allizadrozny/using-webpack-and-react-with-jekyll-cfe137f8a2cc) for an example.
2. Use npm to install the dependencies, and something like a post-install script to copy minified versions to their final destinations
3. Build formation.js locally, and check-in the minified version

**Comment by karlbrown-va** [comment]
see https://github.com/department-of-veterans-affairs/vets.gov-status/pull/3210
