### ISSUE TITLE
Implement VA.gov at a glance - CSAT scores

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3208]
**As** a member of the Office of the CTO
**I want to** present a view of customer satisfaction across various VA.gov tools
**so that** any visitor (such as a senior VA stakeholder) to the dashboard gets an insight into how the veteran experience has been with the portal

**Tasks:**
* Pull CSAT scores across all VA.gov pages, for the last 12 months from Foresee
* Specific query to pull the data is TBD
* Display a <s>line chart</s> bar graph plotting the average score for each month over the last 12 months
* Display an average CSAT score over the last 12 months in bold against the chart (Refer design)
* Include alt text (chart description) for screen readers for 508 compliance

**Acceptance Criteria**
Given any user
When he/she visits the dashboard
Then the visitor sees the Customer satisfaction portion within the 'VA.gov at a glance' section

Given any user
When he/she visits the dashboard
Then the visitor sees Logged in users metrics (Refer design)

Given the data refresh job is run 
When there is an error updating the chart value
Then
- Exit with error code = 1
- Do not refresh the data on the chart and retain the old values
- Do not update the last updated date

**Chart description text (specifically for screen readers)**

This chart displays the total number of logged in users to the various VA services over the last 12 months (from to )
<Month 1>: <Data Value 1>,
<Month 2>: <Data Value 2>,
<Month 3>: <Data Value 3>,
<Month 4>: <Data Value 4>,
<Month 5>: <Data Value 5>,
<Month 6>: <Data Value 6>,
<Month 7>: <Data Value 7>,
<Month 8>: <Data Value 8>,
<Month 9>: <Data Value 9>,
<Month 10>: <Data Value 10>,
<Month 11>: <Data Value 11>,
<Month 12>: <Data Value 12>

**Designs**

![VAGov-Dashboard-3162020 (1)](https://user-images.githubusercontent.com/2493271/76813958-e371d200-67cf-11ea-895f-1ee5c580e9cc.jpg)

**Comment by saman-moshafi-va** [comment]
After talking with Ramya we discovered the need to apply filters to the 'Measure Data' API call. However, filtering is not published for the API.  So I raised a support with ForeSee technical support.  The ticket should be 'using Froesee API #00094114 [ ref:_00D46tfr._5001M1Nd7IK'.
The same person referred to by Chante, Jon Cioffi, picked up the support ticket and is working on answers. Here is the email I sent:
* Using the published ForeSee API I could not find any way to get the CSAT score. 
* Another question which is equally important for the project I am working on is how to apply filter to /measures/data.  E.g. On the dashboard we can filter by ‘url’ and see different CSAT score value.  How can I apply using the ‘Measure Data’ API or a combination of API calls?

**Comment by saman-moshafi-va** [comment]
Using OData is more resilient as one call returns all the required data and it is also possible to filter the data hence it is a lot faster.  
We have communicated to the ForeSee people on how to use a system account to use OData calls.

**Comment by saman-moshafi-va** [comment]
Here are the remaining tasks:
- Finalize whether to use OData or not, we prefer OData
- make sure the yearly graph is displayed at the top
- determine where to save the overall yearly values as the same yml file might be used for both google analytics and ForeSee results
- calculate and provide the data required for the first tile
-
