### ISSUE TITLE
Implement Header & Footer as per the new designs

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3212]
Tasks:

- Header, with a link to va.gov when clicking on the image on the left
- Footer, with no additional links for now, but a VA image as per design. 
- Clicking on the image in the footer takes to va.gov

Last updated date will be built in a follow up story

**Comment by rumyeahs** [comment]
Skeleton layout with columns

**Comment by everthoughtworks** [comment]
closing as redundant as per @toddstanich
