### ISSUE TITLE
Wrap-up documentation before hand off

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3223]
Documentation needed for

- Any maintenance tasks including the credstash issues, others, etc.
- Connection documentation (how the connections are made, work)
- Any recommended security patches
- Basic information about making changes in the YAML file as well as other user facing changes (high level is fine)

**Comment by marisahoenig** [comment]
Final documentation needed:
- Foresee/credstash info - @saman-moshafi-va 
- Deployment (pipeline) - @karlbrown-va

**Comment by saman-moshafi-va** [comment]
working on it

**Comment by saman-moshafi-va** [comment]
We need to add what should be done if measure id is changed.
