### ISSUE TITLE
Implement updated lean footer

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3224]
Lean footer

Links:
- Clicking on **image** should redirect to https://www.va.gov/
- **Go to VA.gov** points to https://www.va.gov/
- **About VA** points to https://www.va.gov/ABOUT_VA/index.asp
- **FOIA points** to https://www.va.gov/foia/
- **Office of the Inspector General** points to https://www.va.gov/oig/
- **Privacy policy** points to https://www.va.gov/privacy-policy/
- **USA.gov** points to https://www.usa.gov/ 

![image.png](https://images.zenhubusercontent.com/5dc98bd276ca1300019e1a85/ae9d3ec4-869d-4359-8755-8e3740a761bc)

**Comment by toddstanich** [comment]
Footer design specs attached. 

<img width="1538" alt="footer-specs" src="https://user-images.githubusercontent.com/56000470/76792188-7ee35280-6790-11ea-8204-2d4e7e251516.png">

**Comment by katieho-va** [comment]
So the "Built by the Digital Experience Product Office" text goes away? @toddstanich

**Comment by toddstanich** [comment]
@katieho-va yes, we can remove it.

**Comment by katieho-va** [comment]
@toddstanich Do you have a mockup for how the links should look when the screen is smaller? All stacked or all under the logo?

**Comment by toddstanich** [comment]
@katieho-va Here is a mobile mockup

![VAGov-Dashboard-Mobile-Footer](https://user-images.githubusercontent.com/56000470/76795012-3fb80000-6796-11ea-9ef9-18cf88929cc9.jpg)

**Comment by everthoughtworks** [comment]
Verified on all devices specified in: https://docs.google.com/spreadsheets/d/1cyVQh7XPlxI2FNjxWzMsCMr2toHawcAtQqzyilTGuPw/edit#gid=0
