### ISSUE TITLE
508 issues

### ISSUE THREAD

**Issue by everthoughtworks** [department-of-veterans-affairs/vets.gov-status#3225]
![Screen Shot 2020-03-16 at 4.29.59 PM.png](https://images.zenhubusercontent.com/5dd6a3bbefbeb900016ca508/9d0233e5-d7aa-4b31-aaba-a719ee1328fe)

Current 508 issue status, that can be obtained using the axe chrome plugin: https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US

**Comment by everthoughtworks** [comment]
Additionally: Tab button does not work on safari, on Firefox it skips most of the elements, on Chrome one of the graph views @marisahoenig

**Comment by marisahoenig** [comment]
@everthoughtworks In safari, you need to use option + tab or set up using tab in preferences. I see the same functionality as chrome using option + tab. 
https://osxdaily.com/2011/08/14/enable-tab-key-navigation-safari/

**Comment by katieho-va** [comment]
@everthoughtworks Apparently for Firefox on Mac, the tabbing needs to be set as a preference on the machine. Firefox on Windows works fine though. 

http://www.weba11y.com/blog/2014/07/07/keyboard-navigation-in-mac-browsers/
"In Safari and Chrome the browser preference for tab key navigation takes precedence. In Firefox the user must modify the OS X system preference for tab key navigation to links and controls within the content."
