### ISSUE TITLE
Update design changes to the dashboard

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3226]
Refer updated design attached to the card:

1. Change VA.gov at a glance charts to Bar charts
    1. Include 0 on the y-axis
    2. The text style for the highlighted text on the left of each chart is now tab style 
2. Include “How is this measured?” section under VA.gov at a glance 
    1. Refine the text with Chante
3. Include new header for Service line metrics: Performance by service
    1. Include “How is this measured?” section 
    2. Change accordion style to card style for each service line tile 

![VAGov-Dashboard-3162020 (1).jpg](https://images.zenhubusercontent.com/5dc98bd276ca1300019e1a85/7de147d3-abf0-4f44-b66a-32fb91578000)

**Comment by toddstanich** [comment]
Specs attached

![VAGov-Dashboard-specs](https://user-images.githubusercontent.com/56000470/76872132-ffaa5900-6839-11ea-9e27-6f64772df159.jpg)
![VAGov-Dashboard-specs2](https://user-images.githubusercontent.com/56000470/76872139-02a54980-683a-11ea-8127-c160b2a7935a.jpg)
![VAGov-Dashboard-text](https://user-images.githubusercontent.com/56000470/76872142-033de000-683a-11ea-899b-7a6711ca1046.jpg)

**Comment by toddstanich** [comment]
Mobile view attached

![VAGov-Dashboard-Mobile-3172020.jpg](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/d41124ef-cb93-4769-8fd0-2cc517b350e7)
