### ISSUE TITLE
List of outstanding issues

### ISSUE THREAD

**Issue by everthoughtworks** [department-of-veterans-affairs/vets.gov-status#3230]
- [x] [1] - North star not visible on mobile (Iphone, Android)
- [x] [2] - Footer on Edge is off on version 16, but fine on version 18
- [x] [3] - Footer moves up leaving blank space underneath on chrome 42
- [ ] [4] - IE 11: footer is not displayed correctly and graph disappears intermittently
- [x] [5] - X axis under the graph does not show up on mobile devices

**Comment by marisahoenig** [comment]
#1 is fixed w/ this commit:
https://github.com/department-of-veterans-affairs/vets.gov-status/commit/f5d69e6c0fa6a818fa4a410606335f6b71e9de8a

**Comment by katieho-va** [comment]
@everthoughtworks can you attach the list of approved browsers/versions to this card?

**Comment by katieho-va** [comment]
#3 is not an issue I'm seeing on BrowserStack. @everthoughtworks can you re-confirm?

**Comment by marisahoenig** [comment]
@everthoughtworks We think #3 is not longer an issue because the content is never shorter than the page height with the new stuff added.

**Comment by katieho-va** [comment]
#2 is fixed with the above two commits 
https://github.com/department-of-veterans-affairs/vets.gov-status/commit/07549bbf1f87f73e7588ae391828cc15b46f4699

https://github.com/department-of-veterans-affairs/vets.gov-status/commit/b702f323cfed5acbb0ec9f7a63c00b5ec395e4ae

**Comment by marisahoenig** [comment]
Created new bug card for #4 (IE 11) after discussion in dev huddle that this can be completed at a later time:
https://github.com/department-of-veterans-affairs/vets.gov-status/issues/3249
