### ISSUE TITLE
Implement total number of transactions for Schedule and View VA Appointments online

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3235]
**As** a member of the Office of the CTO
**I want to** present the total number of successful transactions by veterans and beneficiaries scheduling VA appointments online
**so that** any visitor (such as a VA Senior stakeholder) to the dashboard gets an insight into how many veterans (& beneficiaries) are seeking healthcare applications related benefits from VA.gov

**Tasks:**

- This should provide the count of all Scheduling VA appointments related successful transactions on va.gov/health-care/schedule-view-va-appointments
- Display the total number of successful transactions within the last **30 days** (similar to the timeframe on VA.gov at a glance section) within the Health-care tile on the dashboard (Refer design)
- The UI label should say 'Schedule and view VA appointments online'
- Page Path URL: regex: /schedule-view-va-appointments
- Event Category filter = regex: Transactions
- Event Action filter = regex: Forms

**Tech notes:**

**Acceptance Criteria**
Given any user
When he/she visits the dashboard
Then the visitor sees the section 'Healthcare' section on the page, alongwith the corresponding icon for Healthcare

Given any user
When he/she visits the dashboard
Then the visitor sees total successful transactions for scheduling and viewing VA appointments online for the last 30 days (Refer design)

Given 
When there is an error updating the chart value
Then 
- Exit with error code = 1
- Do not refresh the data on the chart and retain the old values 
- Do not update the last updated date

**Designs**
<img width="953" alt="Screen Shot 2020-03-18 at 8 15 28 AM" src="https://user-images.githubusercontent.com/2493271/76971447-9727ae80-6903-11ea-9922-22b659a5589a.png">

**Comment by marisahoenig** [comment]
Work being tracked on https://github.com/department-of-veterans-affairs/vets.gov-status/issues/3202
