### ISSUE TITLE
Visual QA

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/vets.gov-status#3242]
- [x] Reduce height of header (dark blue background) to 100px
~~- [ ] On mobile, increase size of logo - work with Todd on sizing~~ 
- [x] Increase width of the content area to 1000px on desktop. Other va.gov pages are 1000px wide. It looks like we have some extra padding causing the content to fill less space.
- [x] On mobile, "Our North Star" text size decreases. It should react the same way as "va.gov at a glance" and "performance by service" and not reduce in size.
- [x] VA.gov at a glance customer satisfaction y-axis is missing padding.

**Comment by katieho-va** [comment]
@toddstanich Can you provide more details on this point?

_On mobile, "Our North Star" text size decreases. It should react the same way as "va.gov at a glance" and "performance by service" and not reduce in size._

Should the header "VA.gov | Performance Dashboard" also not decrease in size?

**Comment by katieho-va** [comment]
Should "Our North Star", "VA.gov at a glance" and "Performance by Service" all be the same font size 32px? They are currently off

**Comment by toddstanich** [comment]
@katieho-va ""Our North Star", "VA.gov at a glance" and "Performance by Service" all be the same size (32px). 

"VA.gov | Performance Dashboard" can stay as it it, I just checked and it cannot be larger without wrapping on small devices. I'll cross out point #2 on this ticket.

**Comment by katieho-va** [comment]
@toddstanich thanks! Just to clarify, "VA.gov | Performance Dashboard" text should be responsive for smaller screens or stay at 32px like the other big headers?

**Comment by toddstanich** [comment]
@katieho-va It should be responsive for smaller screens and stay as it currently functions.

**Comment by katieho-va** [comment]
@toddstanich got it, thanks!

**Comment by katieho-va** [comment]
@toddstanich Can you send a screenshot of this one? I'm not seeing extra padding on desktop. I think the current width of the content area is greater than 1000px already?

_Increase width of the content area to 1000px on desktop. Other va.gov pages are 1000px wide. It looks like we have some extra padding causing the content to fill less space._

**Comment by katieho-va** [comment]
@toddstanich Added the 1000px spec, feel free to play around with it. I'm looking into the chart cols.

**Comment by toddstanich** [comment]
@katieho-va the increase in width does not look like it applied to the footer or the "An official website of the United States government" banner.

Verified all other changes and they look good.

**Comment by katieho-va** [comment]
@toddstanich will fix footer

**Comment by katieho-va** [comment]
@toddstanich Shefali/Saman and I updated the footer and header, please review again

**Comment by toddstanich** [comment]
Verified, thanks!
