### ISSUE TITLE
Implement 'How to measure' text

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/vets.gov-status#3243]
VA.gov at a glance:

**Logged in users**: The total count of all users who have logged in to VA.gov over the last 12 months, using ID.me or MyHealtheVet or DS Logon

**Successful transactions**: The total count of completed actions taken on VA.gov over
the last 12 months. This includes applications submitted (e.g. health care,
education, etc.), health appointments scheduled, claims status checked, benefit
letters downloaded, and all other transactions completed using VA.gov tools.

Performance by Service:

**How is this measured**

**Total users**: The count of total users to the various service lines such as Health Care, Education, Pension, etc. on the VA.gov portal over the last 30 days

**Customer satisfaction**: An average customer satisfaction score based on the feedback responses from users within the various service lines on the VA.gov portal over the last 30 days

**Transactions**: The total count of user actions such as submitting an application, downloading a form, scheduling an appointment as indicated by the specific tool.

**Comment by toddstanich** [comment]
<img width="893" alt="Screen Shot 2020-03-20 at 9 26 29 AM" src="https://user-images.githubusercontent.com/56000470/77173041-ea793880-6a8c-11ea-9858-12d773b2827f.png">

**Comment by everthoughtworks** [comment]
Verified on MAC: FF, Safari, Chrome
Verified on Windows: FF, Chrome, Edge...does not work on IE11,

**Comment by katieho-va** [comment]
Need to make the additional info work in IE 11

**Comment by marisahoenig** [comment]
Confirmed this looks good on IE 11 and on the GFE IE 11
