### ISSUE TITLE
Add documentation on updating Services tiles

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/vets.gov-status#3255]
Add some information to the README about how to update `services.yml` to see changes reflected in the page - GA regexes, lists of tools, dynamic content, that kind of thing.

**Comment by shefalinayak** [comment]
@philherbert `page_path_filter` for each is not currently optional, I think it will raise a key error in the python script. Should we add back the check and only run the user query if `page_path_filter` is provided?
