### ISSUE TITLE
Represent user satisfaction scores with a better eye towards recent changes

### ISSUE THREAD

**Issue by kennedycollins** [department-of-veterans-affairs/vets.gov-status#3348]
We've gotten some feedback that showing an average CSAT for the last 12 months in the VA.gov at a glance section in confusing, since customer satisfaction is more of a point-in-time metric. We'd like to find a way to better represent the current CSAT while also having that section respect the 12 month timescale of the rest of the metrics.

I'm thinking either:
Current with 12 month change, like we do down below for other stuff, or
Some sort of recency-weighted average, or
Some other idea that one of our smart teammates comes up with.

I expect this will have two parts:
- Change the metric
- Change the how this is measured text. 

We should also figure out if we need to update the text for logged in users

----
Update: We're going with a pretty simple solution:
- [x] Adding time scale labels to the tabs in VA.gov at a glance ("Last 12 Months" for logged in users and transactions; "Last Month" for CSAT"). We can do these as h3s, it looks p. good that way and Todd is on board with it.
- [x] Showing just the most recent month's score in the CSAT tab

<img width="1435" alt="Screen Shot 2020-04-27 at 1 30 27 PM" src="https://user-images.githubusercontent.com/5778867/80504015-3f378b00-8938-11ea-99dc-79e45c3bf07a.png">

**Comment by marisahoenig** [comment]
@kennedycollins Since User Satisfaction is now going to be for the last month, should the "How is this measured?" text also be updated? Right now, it reads "An average user satisfaction score based on the feedback responses from users within the various service lines on VA.gov for the last 12 months." The graph is the last 12 months but the title will be only one month.

**Comment by kennedycollins** [comment]
Good catch — let's change it to "A monthly average user satisfaction score based on the feedback responses from users within the various service lines on VA.gov." 

(Just pulling off 12 months from the end and adding monthly to the front).

**Comment by marisahoenig** [comment]
Thanks, just pushed that text change!
