### ISSUE TITLE
Incorporate migration status dashboard into new format

### ISSUE THREAD

**Issue by robertfairhead** [department-of-veterans-affairs/vets.gov-status#34]
kelly via slack: can put this somewhere more prominent?  "migration status" http://ec2-54-165-153-226.compute-1.amazonaws.com:8080/jekyll/update/2016/01/27/high-level-dashboard.html

**Comment by koconnor719** [comment]
for the migration metrics change to:

- 39 products delivered since Nov. 2015
- 90 day VA release cycle reduced to weekly vets.gov release cycle

**Comment by robertfairhead** [comment]
Added migration metric tiles

**Comment by robertfairhead** [comment]
copied migration status page into our repo as is to prevent any dead links if the random EC2 box that used to host it gets taken down in #148

per @koconnor719 no additional engineering work to be expended on this.
