### ISSUE TITLE
Employment Center Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#40]
* Chart: Active Users
* Chart: Mobile vs Desktop Sessions

A comparison for active users should be possible. @koconnor719: Who do we need to work with to get va.gov GA numbers?

Note that there are no small tiles here, just two large charts.

**Comment by koconnor719** [comment]
we have a lot of GA data on this one. here's some old decks i have w/ VA.gov stats:
[VEC Statistics Presentation 20160216.pptx](https://github.com/department-of-veterans-affairs/vets.gov-status/files/485257/VEC.Statistics.Presentation.20160216.pptx)

[VEC Statistics Presentation 20160418 - Example 3.pptx](https://github.com/department-of-veterans-affairs/vets.gov-status/files/485255/VEC.Statistics.Presentation.20160418.-.Example.3.pptx)

![employment analytics](https://cloud.githubusercontent.com/assets/13770771/18714720/b81c47f6-7fe4-11e6-801e-80ceb9793116.png)

**Comment by cmgiven** [comment]
Is it possible to get direct access to VA? Those presentations don't contain the key number I'd be looking for (number of active users by week).

**Comment by koconnor719** [comment]
@MarinaMartin can you answer this for chris?  i don't know how we access VA.gov google analytics.

**Comment by koconnor719** [comment]
also we could add a cost metric here if @MarinaMartin agrees?  we saved the VA like $8M on this tool.  the vendor estimate to build this was $8M and many months; our team (marina) built and launched in lets say 2 weeks?  so the cost of her salary to do that could be comparison number of $6,000.    :)

**Comment by robertfairhead** [comment]
Added tiles for $8m in savings and mobile availability

**Comment by koconnor719** [comment]
@robertfairhead @gnakm we have wrong before here:)  it's VR&E.   gina do you have screenshots of the old VEC??  a really bad one:)

one additional metric we could add is delivery speed:  Vendor estimate 1 Year to Deliver; Vets.gov delivered in 1 month.

**Comment by robertfairhead** [comment]
Added saving and delivery time tiles. Before screenshot was placeholder. Will update when before shot is provided.

**Comment by koconnor719** [comment]
@robertfairhead per comment above on VR&E (before screenshot)--that's not employment center:)  we'll need a different before screenshot for VEC. @gnakm was design lead on that--hopefully she has an old one she can dig up??  (help gina!)

**Comment by koconnor719** [comment]
@robertfairhead found our VEC Before screenshot--thanks to emdash! 

<img width="705" alt="screen shot 2016-09-27 at 10 53 34 am" src="https://cloud.githubusercontent.com/assets/13770771/18879048/f30654ea-84a0-11e6-8af3-c61dab9bc841.png">

**Comment by robertfairhead** [comment]
Added the before screenshot
