### ISSUE TITLE
Content Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#41]
* Big Number: *524* - websites consolidated into a single, consistent experience
* Screenshots: Comparison between old and new language. Expected from the content team.
* Icon: Mobile Availability - Vets.gov is designed to work equally well on desktop and mobile devices
* Chart: Mobile vs. Desktop Sessions for the entirety of Vets.gov

**Comment by koconnor719** [comment]
@dannychapman works closely w/ content team so he knows a lot about this.  

i think the big things here are plain language, mobile, and consolidating relevant content from 524 sites (will be done in March 2017 fyi); right now we are 75% done w/ content migration. 

content team can provide a really bad (dense, legalese) page before and a good one on vets.gov now--maybe an "apply" page?  or something really clean?  i defer to danny on this:)

**Comment by robertfairhead** [comment]
Added the consolidated sites, mobile, and plain language points. temporary content screenshot until i get a new one from content team.

**Comment by koconnor719** [comment]
@robertfairhead i think we need better screenshots here--especially the after one for vets.gov.   i defer to So company or danny .

**Comment by koconnor719** [comment]
@robertfairhead here are the content screenshots per slack exchange:)

**Comment by robertfairhead** [comment]
Updated metric tiles and screenshots.

**Comment by koconnor719** [comment]
this page looks good in terms of the data:)

**Comment by koconnor719** [comment]
sorry bob, mary ann sent me a better "before" screenshot pls:)


![](https://files.slack.com/files-pri/T03FECE8V-F2GJW4W5T/pasted_image_at_2016_09_27_01_16_pm.png)

**Comment by robertfairhead** [comment]
I added that in as the "after" for content

**Comment by maryannbrody** [comment]
@robertfairhead Can we please change the main sentence from "100% content rewritten in plain language..." to this: 

"We create content to help users accomplish their goals — using words that Veterans know and understand. We develop and prioritize content based on data from user research, VA call centers, and website analytics."

cc/ @koconnor719

**Comment by robertfairhead** [comment]
@maryannbrody 👍 updated it. take a look; the second sentence makes it a bit taller than the other tiles.

**Comment by koconnor719** [comment]
@maryannbrody @robertfairhead 

bob, i think what mary ann wanted was to add that long text above  to replace the back of card metric to replace "100% plain language"  .  not put all that text on front of card:)  (we want to stick to 1 sentence on front of all cards.)

for the short front sentence on card, let's say "More than 500 pages of content rewritten using plain language guidance."  

mary ann i really think we need to use the words "plain language" somewhere on the content card if you are ok with that? (is there a better word than "guidance" -- best practices?  tenets?  principles?  feels super consutanty:(

**Comment by robertfairhead** [comment]
I added in the shorter tag for the front of the card and replaced the 100% plain language tile with the sentences from mary ann. the resulting tile is a bit long as well.

![screen shot 2016-10-03 at 8 11 24 am](https://cloud.githubusercontent.com/assets/6646098/19036899/00e1b920-8941-11e6-8f98-0fa3b28e9fc0.png)


I'd suggest we use those two sentences either in the blue header section or as a subhead to the Featured Improvements section title (similar to the sentence under Access Improvements on the main page). There's more space in those spots for two sentences, but up to you all.

**Comment by koconnor719** [comment]
the text is too long. can we do something here that's inconsistent w/ rest of cards:  put the long text in the blue box above (as you suggest)  but NOT have it appear on front of card (leave that to be the 500 pages thing...)  and then in the third metric box replace the long text w/ "500" and have the title be "plain language" and the text below be " pages of content rewritten using plain language guidance.
@robertfairhead

**Comment by robertfairhead** [comment]
@koconnor719 yes, definitely. i will make that update this afternoon.

**Comment by robertfairhead** [comment]
Left front of card the same. Made the description on detailed page be the longer, two sentence version. added the new third tile.
