### ISSUE TITLE
GI Tool Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#42]
* Image Comparison: Screenshots attached
* TBD
* Icon: Flag — VA can add "caution flags" to schools in real time
* Chart: Active Users (comparison should be possible, yes? @koconnor719)

We need one more small item here.

Before:
<img width="1350" alt="screen shot 2016-09-20 at 10 24 15 am" src="https://cloud.githubusercontent.com/assets/5375557/18713281/bb520c6c-7fdf-11e6-8d6e-b31c42c570ae.png">

After:
<img width="932" alt="screen shot 2016-09-20 at 10 28 02 am" src="https://cloud.githubusercontent.com/assets/5375557/18713293/c8d59912-7fdf-11e6-8d5a-f76ff168b476.png">

**Comment by cmgiven** [comment]
Perhaps something about using open data?

**Comment by koconnor719** [comment]
can we call out the school "ITT" for caution flags as an example if possible (high visibility in news). i

**Comment by cmgiven** [comment]
Wonder if @dannychapman has thoughts on that one? How might we include that sort of example in a description of the flagging feature?

**Comment by koconnor719** [comment]
the idea is that the tool doesn't just tell Veterans how much a school costs w/ GI Benefit--but more importantly is the school performing well--and worth the value???

**Comment by robertfairhead** [comment]
Added caution warning and screenshots and traffic charts

**Comment by koconnor719** [comment]
sorry --let's take out the reference to ITT...it doesn't seem right now that i see it.  sorry!

**Comment by koconnor719** [comment]
- for the caution flag metric--the improvement is that it's real time--VA can update this immediately.
- Before: release cycle 90 days ; after weekly

**Comment by robertfairhead** [comment]
Removed ITT, updated language with realtime, added release cycle tile

**Comment by koconnor719** [comment]
@robertfairhead  needs a third metric:

- Provides Veterans with performance measures on schools.

**Comment by robertfairhead** [comment]
Added third metric
