### ISSUE TITLE
Health Application Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#43]
* Icon: Mobile Availability - Veterans can now complete their application entirely from a smartphone
* Comparison: before - 12%, after - 50% of submissions processed automatically and immediately
* Image Comparison
* Chart: Monthly Submissions (comparison: 7,620)
* Chart: Active Users

@koconnor719: Can you confirm that the comparison values are correct?

**Comment by koconnor719** [comment]
one HCA metric needs to be in the top "Access" section w/ i'm thinking a pie chart?  (if that's the best visualization?) we will go from 10% (of 582,000 health care apps in 2015) submitted online to 50% online (projected based on current submission data) in 2017.

comparison:  baseline metric :  average of 62 daily submissions using VOA (old VA thing--veteran online application) ; our vets.gov metric is a daily average of 495 right now.

also we've been as high as 831 / day.

i sent you screenshot for this before and after.

**Comment by cmgiven** [comment]
Thinking that submission numbers can be shown in the chart, with the comparison number to get at the total number of online submissions. Because this cannot (yes?) be automatically processed, probably don't want to get more granular than monthly.

Does the combination of the absolutely number of online submissions + the percentage of submissions processed automatically get us where we need to be? Or should we include an additional metric?

The new before screenshot, attached.
<img width="1152" alt="screen shot 2016-09-20 at 11 02 12 am" src="https://cloud.githubusercontent.com/assets/5375557/18715063/e2ac6b08-7fe5-11e6-9211-6a08374ba55c.png">

**Comment by robertfairhead** [comment]
Updated before screenshot and automatically processed submissions. The before/after pie charts are still a little wonky. Will update to those from text for the online percentage of submissions once i get that fixed

**Comment by koconnor719** [comment]
@robertfairhead  for the automatically processed applications; let's just change to average daily online submissions: 62 / day ; 500 per day.

replace mobile with online form completion time: before 45-60 minutes ; after 12-22 minutes.

**Comment by robertfairhead** [comment]
Updated cost per year, daily submissions, and minutes to complete tiles

**Comment by koconnor719** [comment]
@robertfairhead 

for cost per year, let's say $30K (having both be 8's is weird)--and i recalculated this:)

per anne's comment, let's replace third metric (minus to complete) with the following:

30,000 online applications in 60 days

**Comment by robertfairhead** [comment]
Updated to $30k and replaced third metric
