### ISSUE TITLE
Facility Locator Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#44]
* Number: 20 - locator tools consolidated into a single experience
* Now includes services (@koconnor719: What does this mean?)
* Icon: Mobile Availability - Works equally well on desktop and mobile devices
* Chart: Active Users

**Comment by koconnor719** [comment]
there are 43 locators; our MVP won't consolidate them. before vets could only search locations of VA facilities--now they can search both--lcoation and see if the service they need is at that location.  i think the big improvement there was using Google maps right?  @dannychapman

**Comment by koconnor719** [comment]
we need a before and after screenshot--ours will look better. here's some of the other locators.  
[2017-07.FacilityLocatorList.xlsx](https://github.com/department-of-veterans-affairs/vets.gov-status/files/485221/2017-07.FacilityLocatorList.xlsx)

**Comment by cmgiven** [comment]
The screenshots should replace the mobile availability icon.

**Comment by robertfairhead** [comment]
I added the dual search options and consolidation tiles. There is google analytics data on this, but it will require some additional GA configuration before I can add that it in. Should be done by Monday.

**Comment by koconnor719** [comment]
@robertfairhead we need a better "after" screenshot here:)  @gnakm help!  https://adhocteam.github.io/vets.gov-status/boards/facility.html

**Comment by gnakm** [comment]
Hey all~ here are screenshots of the new design BUT seeing that our scope is changing, there will be some visual changes. Hope the images below are helpful. Let me know if guys need other images!

Search
<img width="401" alt="screen shot 2016-09-23 at 10 42 23 am" src="https://cloud.githubusercontent.com/assets/13420618/18789873/99c85f1e-817a-11e6-9f3e-a6bc38351b00.png">

Search Results list view
<img width="416" alt="screen shot 2016-09-23 at 10 42 57 am" src="https://cloud.githubusercontent.com/assets/13420618/18789876/a00b9f1c-817a-11e6-9d2e-a40bdd8981d5.png">

Search Results map view
<img width="403" alt="screen shot 2016-09-23 at 10 43 12 am" src="https://cloud.githubusercontent.com/assets/13420618/18789881/a8f9f3da-817a-11e6-8ff1-7ec0d1ff1493.png">

Facility Detail Page
<img width="408" alt="screen shot 2016-09-23 at 10 43 20 am" src="https://cloud.githubusercontent.com/assets/13420618/18789891/aef6a6a2-817a-11e6-85c0-9f9cfd52af45.png">

From any of the results tab or detail page, users can click `direction` which will redirect them to google maps.
<img width="410" alt="screen shot 2016-09-23 at 10 43 27 am" src="https://cloud.githubusercontent.com/assets/13420618/18789899/b7aa08ac-817a-11e6-9653-f24f88ce2860.png">

**Comment by dannychapman** [comment]
@gnakm These look great BTW!

**Comment by koconnor719** [comment]
Yeah Gina!!!



Sent with Good (www.good.com)


-----Original Message-----

**Comment by koconnor719** [comment]
third metric for this tool is that it now uses Google Maps so:

Before: did not provide driving directions or time; now it does.  (someone else can rework this--i'm not an expert in google maps)

**Comment by robertfairhead** [comment]
Added new after screenshot, third tile on Google maps integration

**Comment by koconnor719** [comment]
looks good!
