### ISSUE TITLE
Prescription Refills Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#46]
* Screenshot comparison (needed)
* Icon: Increased security - Now support two factor authentication
* Decrease in call center volume (needed)
* Chart: Active Users (comparison should be possible)

@koconnor719: Two needed items here.

**Comment by koconnor719** [comment]
@gnakm can you provide chris some good "before and after" screenshots for MHV prescription refill pls.  pls. pick worst before page:)

**Comment by koconnor719** [comment]
let's take out TFA.  let's highlight mobile for this one.

we have baseline data for this; i have to find it.

**Comment by cmgiven** [comment]
Makes sense. Note that we're bragging on mobile a lot. Included 2FA for variety, which is not the best reason, but we'll want to swap out mobile with something else where possible.

**Comment by koconnor719** [comment]
got it.  i'm not sure we are launching TFA in Nov:)

**Comment by gnakm** [comment]
@cmgiven Here are some screenshots

## MHV

### Landing Page

<img width="1186" alt="screen shot 2016-09-21 at 3 02 16 pm" src="https://cloud.githubusercontent.com/assets/13420618/18725032/ad57f84c-800c-11e6-9476-f87f28fa7302.png">

### Refill Prescriptions
<img width="1188" alt="screen shot 2016-09-21 at 3 02 39 pm" src="https://cloud.githubusercontent.com/assets/13420618/18725044/b61ab654-800c-11e6-808a-ef4b042963b7.png">

### Prescriptions History

![my healthevet](https://cloud.githubusercontent.com/assets/13420618/18725256/88610e06-800d-11e6-8eaf-2a96e4c60f0e.png)

### Prescriptions Tracking

<img width="1187" alt="screen shot 2016-09-21 at 3 03 35 pm" src="https://cloud.githubusercontent.com/assets/13420618/18725217/5586ed84-800d-11e6-8609-f0c1e00f7f10.png">

## Vets.gov

### Refill Prescriptions

![refill your prescriptions vets gov](https://cloud.githubusercontent.com/assets/13420618/18725416/32763bd2-800e-11e6-89a7-60ab1bab2ea2.png)

<img width="190" alt="screen shot 2016-09-21 at 3 20 55 pm" src="https://cloud.githubusercontent.com/assets/13420618/18725617/07ad7950-800f-11e6-9756-2d55d0cfce88.png">


### Refill History

![refill your prescriptions vets gov2](https://cloud.githubusercontent.com/assets/13420618/18725513/8817d514-800e-11e6-918e-066cb991e32c.png)

<img width="185" alt="screen shot 2016-09-21 at 3 18 34 pm" src="https://cloud.githubusercontent.com/assets/13420618/18725548/b5860ab6-800e-11e6-80f8-c0fd3141e40c.png">

### Prescription Detail

![refill your prescriptions vets gov detail](https://cloud.githubusercontent.com/assets/13420618/18725557/bedde43a-800e-11e6-94d9-8e9e3dae551e.png)

<img width="202" alt="screen shot 2016-09-21 at 3 17 02 pm" src="https://cloud.githubusercontent.com/assets/13420618/18725498/7de641e8-800e-11e6-936c-a3fe35a45591.png">

**Comment by robertfairhead** [comment]
Added the mobile access and screenshots. Will add GA charts once site is live.

**Comment by koconnor719** [comment]
@robertfairhead for the screenshots--can we do a mobile view for the before / after?  MHV is not mobile--so that before should be awful.  @gnakm

**Comment by crwallace** [comment]
@koconnor719 -- We can do a quick scan on MHV. If we get a url and whatever credentials we are using, I can run a scan tomorrow.

**Comment by koconnor719** [comment]
That would be awesome!!! Where do u think is most compelling story w 508?? We can highlight in 2-3 places if you have some good ones!!



Sent with Good (www.good.com)


-----Original Message-----

**Comment by robertfairhead** [comment]
Added mobile screenshots.

**Comment by koconnor719** [comment]
pls. use this image (with name of drug--rather than "drug 2"

@robertfairhead 

https://files.slack.com/files-pri/T03FECE8V-F2FTMF9J7/screen_shot_2016-09-26_at_9.37.01_am.png

**Comment by koconnor719** [comment]
<img width="183" alt="screen shot 2016-09-26 at 9 37 01 am" src="https://cloud.githubusercontent.com/assets/13770771/18838066/0980734a-83d4-11e6-8e92-9119194cc6f3.png">

**Comment by koconnor719** [comment]
on prescriptions card, change the sentence to "Veterans can refill their VA prescriptions from any device"

  The "any device" part is more preference so could go either way, but changing "medicine" to "VA prescriptions" does seem to make it more accurate.

**Comment by koconnor719** [comment]
we need 2 more metrics on this card?

**Comment by cmgiven** [comment]
If referencing my original post, I was just flagging that we needed additional information about two of the proposed metrics.

**Comment by koconnor719** [comment]
this would be a target metric:  Convert VA call center phone refills (more than 2M / year) to online prescription refills.

**Comment by robertfairhead** [comment]
Updated screenshot; tagline/metric language; and added call center metric

**Comment by koconnor719** [comment]
can we use a more exact number for call center calls 2,1M calls?  (i just got the real number 2,117,253).

we need a third metric here--let's ask stacey tomorrow:)

**Comment by robertfairhead** [comment]
Updated to 2.1M calls
