### ISSUE TITLE
Education Application Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#48]
This is a stub, will launch in November

* Number comparison: Uptime (we'll use whatever we're comfortable with for the after, but I imagine it'll be some number of nines).
* Screenshot comparison
* Usability test results? Can we get an average time to completion?
* Chart: Active users

**Comment by koconnor719** [comment]
not flippable? i will review when ready:)

**Comment by koconnor719** [comment]
for additional metric add:

- for the caution flag metric--the improvement is that it's real time--VA can update this immediately.
- Before: release cycle 90 days ; after weekly

**Comment by koconnor719** [comment]
https://github.com/akainic can we pls. provide some Veteran quotes from usability testing?

**Comment by koconnor719** [comment]
@akainic  or @cweber can you pls post our best screenshot here for EDU 1990 form for Bob to put in scorecard:)  it doesn't have to be final it just needs to look really great:)  (fyi here's the page:  https://adhocteam.github.io/vets.gov-status/boards/eduapply.html )

**Comment by koconnor719** [comment]
ok, for metrics:

- mitigated security issues on legacy site (VONAPP)
- improved design and Veteran user experience
- Quote from usability testing

(we could also highlight mobile here--but can't do this in too many places:)

**Comment by akainic** [comment]
@koconnor719 @robertfairhead Does one of these screenshots work? One just includes the Vets.gov banner and the other does not. I tried to include questions in the screenshot that are particular to the education form (benefit selection).

<img width="1305" alt="screen shot 2016-09-22 at 9 23 40 am" src="https://cloud.githubusercontent.com/assets/3886085/18855841/ee24dba4-8423-11e6-9087-21f37c1c245a.png">


<img width="1181" alt="screen shot 2016-09-26 at 7 59 02 pm" src="https://cloud.githubusercontent.com/assets/3886085/18855824/c3257b0c-8423-11e6-9503-fb45c01ff714.png">

**Comment by koconnor719** [comment]
Thx Anne!!! These r great!



Sent with Good (www.good.com)


-----Original Message-----

**Comment by robertfairhead** [comment]
Added tiles and screenshot. Quote tile is still a placeholder for now.
