### ISSUE TITLE
Benefits Claim Status Metrics

### ISSUE THREAD

**Issue by cmgiven** [department-of-veterans-affairs/vets.gov-status#49]
This is a stub, will launch in November.

* Chart: Active Users

**Comment by robertfairhead** [comment]
Left as coming soon

**Comment by koconnor719** [comment]
@robertfairhead 

this card is not flippable so i can't see what's there.  but here's some metrics:

- before 90 day release cycles; after weekly releases.
- before availability: X number (josh might be able to get this--it should be very very low?); after 99.99%

- Josh Q can get you some good before / after screenshots. (sorry he's not in this repo or i'd tag him)

**Comment by robertfairhead** [comment]
Do you want left as coming soon per chris's original or do you want to make it flippable?

**Comment by koconnor719** [comment]
@robertfairhead  let's build this one out please:) 

here are the metrics:
- 90 day release cycle before; 7 after
-improved availability (need this before number from josh q--i don't know it) i'll slack him.
- reduce call center calls on claims/appeals of 1.5M calls per year
-

**Comment by robertfairhead** [comment]
updated metrics and added placeholders for screenshots

**Comment by suzchap** [comment]
![ebenefits_claim_status](https://cloud.githubusercontent.com/assets/11219417/18876517/06962cdc-8498-11e6-8fc4-765edb2bcae7.png)

Here's a "before" and I'll get some temporary "afters" from mel...

**Comment by koconnor719** [comment]
Thank you!!!

**Comment by robertfairhead** [comment]
Added the before screenshot

**Comment by suzchap** [comment]
![mobile-status](https://cloud.githubusercontent.com/assets/11219417/18880622/83b698b0-84a6-11e6-98cb-7dcb3afd0698.png)
![desktop-status](https://cloud.githubusercontent.com/assets/11219417/18880623/83b7ad9a-84a6-11e6-89f0-99fefca54d3a.png)

(these are constantly changing so we'll need to swap them out once this is launched)

**Comment by robertfairhead** [comment]
Added after screenshot

**Comment by koconnor719** [comment]
ty:)
