### ISSUE TITLE
Vertical tabs do not work well at lower screen sizes

### ISSUE THREAD

**Issue by robertfairhead** [department-of-veterans-affairs/vets.gov-status#52]
They only really work at desktop size. Will need to flex to horizontal tabs for responsiveness.

**Comment by dannychapman** [comment]
I have a fix just merged for this, but the charts still need work. Can we control the Chart.js sizing via CSS @robertfairhead?

**Comment by robertfairhead** [comment]
@dannychapman i still need to look into it. i may end up swapping in another charting package. there's like a million of them. now that i have a better idea of our exact needs and use case, it should be easier to evaluate the options.

**Comment by robertfairhead** [comment]
In the end i stayed with Chart.js but made the tabs horizontal to fix the resizing issues.
