### ISSUE TITLE
9/21 review notes on homepage

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#58]
bob, i will put comments on individual cards/products in the issues you guys already have going.  here are the general comments on the landing page per our meeting today.  looks so good.  ty.

@robertfairhead

Access
- first sentence "apply for"  (add "for")
- Access sentence: "Improving Veteran access to benefits and services."   (i think that can replace the 2 current sentences.)
-for the first health care metric (10%  and 50%) can we title it "500,000 + annual VA health care applications"; today 10% online; 50% online (projected 2017).  
- for the mobile stat is it "mobile access" ; before 46% of VA websites; after 100% 
-should we add "accessibility" to 508 compliance? (i will add an issue for courtney for a before number)

Traffic
- should we add page views as a third toggle?  these would be higher numbers...
- can we make it more apparent to users they can click on those toggle buttons?  i don't the yellow bar means anything to users?  (it didn't to me)

Migration Status
- for metrics  change title to "Products Delivered to Veterans" and metrics to "Launhed: 20"  and "Backlog: 16"  
- remove links to playbook
- change blue box title to "Migration Status" and sentence to be: "Tracks the legacy products on VA.gov websites that are migrated to vets.gov."

here are the refined sentences for each card:

Search - good as is.
Content - 100% of content rewritten in plain language
GI Bill Comparison Tool- Includes school performance data--and caution flags to warn Veterans
FL - good as is.
Benefits Navigator - Find benefits more easily
Health Care Application - Increased online submissions from 62/day to 500/day.
Education Application - change to "mobile" device
Disbility Claim Status - we need a better sentence here; this is important @suzchap help:)
VCL - delete "from homepage"
Prescription Refill  - need a better sentence here.  i will work on . (@gnakm any really big design improvements you can think of to call out in 1 sentence?)
VEC - good as is
SM  - good as is

**Comment by robertfairhead** [comment]
All updates should applied except for adding page views.

For that:

- Do you want it only on the overall page or all of them?
- What order do you want the three metrics listed in (page views, users, mobile usage)?
- What terminology do you want to use to refer to each (current site traffic would be ambiguous between users and page views)?

**Comment by gnakm** [comment]
@koconnor719 Prescription Refill - Responsive web design and easier prescription experience.

**Comment by koconnor719** [comment]
@gnakm is this a comment in general of for prescription page?

**Comment by koconnor719** [comment]
@robertfairhead i think the main page for the page views pls. i think the tabs should go in the following order:

1. users
moble
page views (i think page views is least telling--but will be highest number:)  

i'll defer to @staceylanger on that.

k

**Comment by gnakm** [comment]
@koconnor719 
RE: Prescription Refill - need a better sentence here. i will work on . (@gnakm any really big design improvements you can think of to call out in 1 sentence?)

The responsive part of prescriptions is a major improvement but since responsive web is a general improvement for Vets.gov maybe it would be better to highlight that the new Rx refill design is cleaner and easier to use for Veterans.

**Comment by koconnor719** [comment]
agreed:)  but we need some data to support that.  we are trying to SHOW why we are better--not just TELL:)

**Comment by robertfairhead** [comment]
added page views to main page and added to automated data pull scripts
