### ISSUE TITLE
search 

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#60]
@robertfairhead search needs a more meaningful search than "veteran"--can we search something like "benefits rating" and show how awful the VA.gov search results are--and how relevant our are? i would have someone do a few searches on top things veterans need w/ the worst results--like links to CFR or legal pdf docs or something:)  so benefits ratings brings up GI Tool.

thx

**Comment by koconnor719** [comment]
<img width="1098" alt="screen shot 2016-09-23 at 9 21 05 am" src="https://cloud.githubusercontent.com/assets/13770771/18787075/30f5a600-816f-11e6-92f0-b1ed30eed047.png">

**Comment by koconnor719** [comment]
metric is 1-click access to top 100 search terms

**Comment by robertfairhead** [comment]
Updated screenshots with benefits rating search and 1-click metric tile

**Comment by koconnor719** [comment]
replace the after screenshot w/ this one (with relevant results:)  the one that's currently show has careers and employment first--if this is really happening than our search is not working???  can you guys pls. check this?  that should not be top result right?  @dannychapman 

![screen shot 2016-09-26 at 7 17 41 pm](https://cloud.githubusercontent.com/assets/13770771/18855087/0feeafcc-841e-11e6-822e-7c92d90a5e13.png)

looks like we need 2 more metrics for search?  @dannychapman can you think of any search stuff??   maybe:
- improved results with better search tool.
--improved display / design of results

**Comment by dannychapman** [comment]
@koconnor719 In this case, if you type disability ratings, it is the first result. My suspicion here is that since we don't map keywords like "benefits ratings" to disability ratings, the search is unable to cross reference the two. This is part of a larger conversation we need to have with the DigitalGov Search team, and internally in terms of meta data.

**Comment by dannychapman** [comment]
@koconnor719 Not sure about specific metrics, since both VA.gov and vets.gov both use DigitalGov search. Display is largely similar too.

**Comment by robertfairhead** [comment]
@dannychapman VA.gov does not use DigitalGov search by default. Default search engine is an internal one. You can click a link off the VA search page to get DigitalGov search results for VA, but the user has to take that action.

**Comment by robertfairhead** [comment]
Updated screenshot

**Comment by dannychapman** [comment]
@robertfairhead ah! good to know. I stand corrected. Do you know if it is a Google search appliance? If so, we could put something together around that in terms of metrics.

**Comment by robertfairhead** [comment]
I don't know off-hand what VA.gov uses.

We do have vets.gov search metrics from DigitalGov. I will take a look there after I'm done with the other updates and see if I can pull in two other tiles here.

**Comment by koconnor719** [comment]
@staceylanger need to confirm we will achieve 1-click access to top 100 search terms.  this is actually on our reporting dashboard as an explicit metric:)

**Comment by koconnor719** [comment]
thx @dannychapman the metric marina defined a while ago was 1-click access to the top VA.gov searches:)

**Comment by dannychapman** [comment]
@koconnor719 Yep, makes sense. Thanks!

**Comment by robertfairhead** [comment]
i added two other metrics tiles based on DigitalGov data for vets.gov just to fill it out for the review today.
