### ISSUE TITLE
Veteran Quotes

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#64]
if we want to provide some ###Veteran quotes somewhere on landing page, here are 2:

- “I’ve tried to fill out the 10-10EZ [VOA] so many times it’s like ridiculous…some Veterans don’t have the finances to upgrade to a computer that carries the most recent version of Adobe…I called the VA and the woman told me, after she had me on hold, that she couldn’t help me.”

- “This [vets.gov online health care application] is super easy. I have not had this level of ease with a website for the government at all. This is awesome…the other website [VOA]… leads you in  back door that’s blocked with spikes and IEDs.”

**Comment by robertfairhead** [comment]
do you want these added? If so on which page to replace what given the 3 tile limit.

**Comment by koconnor719** [comment]
@robertfairhead yes--what do you and danny think??  i think add them on main page--maybe put a blue box (lighter blue?) somewhere where there is space around the other boxes called "Veteran Feedback" ??

**Comment by dannychapman** [comment]
I am happy to style this one. @robertfairhead if you want to stub them out on a branch I can pick up and finish the styling. I'd consider moving it a bit lower down the page though, it's nice to get more of the stats, and the dashboard elements up front. Perhaps we could put it before migration status?

**Comment by robertfairhead** [comment]
I added in a veterans research section on the main page above the migration status field.

@dannychapman welcome thoughts on styling. it's a little repetitive with the migration.

it links through to a research page that could also use a look.

**Comment by koconnor719** [comment]
@maryannbrody unless you have any other quotes?  i think we can close this one.

**Comment by robertfairhead** [comment]
I added the two additional quotes from Edu Applications. Closing now but feel free to open a new one with more quotes.
