### ISSUE TITLE
9.26 notes

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#67]
@robertfairhead 

landing page
- can we use the exact number of 582,000?  the metric is for ONLINE % of applications....so only add "online" to the before and after ; 10% were online in 2015; but 50% are projected online in 2017:)
- traffic: add tab 3 for page views (just on homepage)
- is there any room to add under 508 accessibility "improved experience for blind Veterans"?  i'll leave to your judgement.
-migration dashboard needs the link added.

@robertfairhead 
- for the top metric under access on 508:  change the title to "508 Accessibility Compliance" then under the 100% can you pls. change smaller text to "improved experience for blind Veterans"

cool!  looks like you are changing as I'm typing:)

**Comment by robertfairhead** [comment]
Updated to 582k and clarified online. Added page view tab (just homepage). Updated 508 language. Added link to existing migration dashboard.
