### ISSUE TITLE
9.27 Notes

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#70]
- internal audience only for first release
- no password; not limited to network
- i owe you updates on the following metrics: education, HCA, MHV, SM.
- i owe you disclaimer, (same one on vets.gov pls)  This site is a work in progress (https://www.vets.gov/playbook/design/)
- make the teeny font size a little bigger
- capitalize "i" in improved experience for blind veterans
- correct spelling of Access
- danny to design a row for veteran feedback that does not push traffic too far down page
- mary anne snet me a better after screenshot for content so i'll post that in the content issue
- delete non-flippable card "benefits navigator"
- remove all the "new" labels
-the only ones that should be "coming soon" (and still flippable) are:  education application, disability claim status, prescription refill, secure message, 

@robertfairhead

**Comment by robertfairhead** [comment]
Added disclaimer; embiggened the font; capitalized the "i"; fixed access typo; added initial feedback row (danny to clean up tomorrow); new content screenshot; removed benefits navigator; removed new labels; adding coming soon to just 4

**Comment by MarinaMartin** [comment]
I'd like to suggest flipping the order of the detail page, put the key accomplishment grey boxes at the top and the before/after visual on the bottom.

**Comment by robertfairhead** [comment]
swapped key accomplishments to top and before/after screenshots to the bottom and added a title for the section

**Comment by robertfairhead** [comment]
added row for veteran feedback and detailed page for additional quotes

**Comment by robertfairhead** [comment]
started work with DevOps on deployment: https://github.com/department-of-veterans-affairs/devops/issues/684

no password; no restrictions on access.

**Comment by koconnor719** [comment]
this looks like all done to me--other than confirmation decision on no password; i emailed martin to review final site after Tuesday COB 10/4 so it will have all changes. he'll confirm w/ us on Wed 10/5

**Comment by robertfairhead** [comment]
Confirmed no password.
