### ISSUE TITLE
add sec bob blog post

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#72]
this is a risk mitigation in case the scorecard link gets released externally (if we don't password protect it) we want to make sure we position the scorecard as part of / pertaining to a "beta" site--just like we did w/ vets.gov.

https://www.vets.gov/2015/11/11/why-we-are-designing-in-beta/   

link should be called same thing, "Message from the Secretary"  and @dannychapman will know where best to put it...it's dated but i think it provides context.    maybe somewhere at the very bottom (since it's dated)?? i don't think it should be prominent...so put wherever you think makes sense.

do you think any issues w/ including this link from a design or user perspective?

**Comment by robertfairhead** [comment]
Added this to existing notice banner at the top since it was already there.
