### ISSUE TITLE
link to vets.gov?

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#73]
@dannychapman should there be a link somewhere on dashboard homepage  to vets.gov website homepage?  i know we have links within the cards to the specific pages. 

defer to whatever you think; just wanted to raise suggestion here since i didn't see one?

**Comment by robertfairhead** [comment]
The VA | Vets.gov header logo is a link to vets.gov

**Comment by robertfairhead** [comment]
Transitioned this to the footer from the header because in testing it became confusing. The dashboard header did not return to the dash main. Will change when moving to public vets.gov styles.
