### ISSUE TITLE
facility locator Search, Display and Pins

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#75]
can we center this metric box content?  OR if all metrics are left aligned--(this is what it appears to be on others too) and that's the design best practice--i'll defer to @dannychapman .

just looked odd being left aligned:)

![screen shot 2016-09-30 at 5 21 00 pm](https://cloud.githubusercontent.com/assets/13770771/19007310/526e2bb8-8732-11e6-8a91-71fb10dff2af.png)

**Comment by koconnor719** [comment]
should this also be aligned on page (the mobile screenshot more to the right?)

![screen shot 2016-09-30 at 5 24 02 pm](https://cloud.githubusercontent.com/assets/13770771/19007386/cc891728-8732-11e6-968e-971276dd4be3.png)

**Comment by dannychapman** [comment]
I think we should keep these left aligned for now. I will remove the drop shadow to make it align a little better.

**Comment by koconnor719** [comment]
Sounds good



Sent with Good (www.good.com)


-----Original Message-----
