### ISSUE TITLE
GA info on GI Tool, VEC and HCA needs "page views"

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#77]
missing third tab?  if this is hard to do don't worry about it for initial release...but just pointing out missing.

![screen shot 2016-09-30 at 5 30 24 pm](https://cloud.githubusercontent.com/assets/13770771/19007559/9b0fd406-8733-11e6-81e4-8fdce56f198e.png)

**Comment by robertfairhead** [comment]
Per your decision in #67, i added it to homepage only. I have gone back and added it to the other pages.
