### ISSUE TITLE
HCA metric

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#79]
this is  a nit pic--but important in order to be accurate for the data:

for the before and after daily submissions (super important metric), the before is specific to one system called "VOA" (veteran online application) so we need a qualifier in the before metric..b/c there was another rogue online system that had 192 submissions / day--these weren't automated tho, they went to a manual process... so we can justify the apples/apples comparison of just VOA to HCA (b/c they are both automated solutions) , so  the 62 before number applies just to VOA--which is the system we want to highlight here with that accurate number (which was self reported by VOA)

![screen shot 2016-09-30 at 5 44 31 pm](https://cloud.githubusercontent.com/assets/13770771/19007900/95e1d3ec-8735-11e6-8f2b-2e126f9d60d5.png)

so if you can figure out how to work "Veteran Online Application" in there for the 62  number would be more accurate.  (note this is a hostile group, so i need to make sure they can't raise any issues w/ this number)  maybe an asterisk and a note??  i have no idea;)

just providing background as to why...sorry i know it's going to screw up the graphic. 

@dannychapman

**Comment by robertfairhead** [comment]
Replaced Before with Veteran Online Application
