### ISSUE TITLE
search box sizes

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#80]
box are different sizes

![screen shot 2016-09-30 at 5 49 59 pm](https://cloud.githubusercontent.com/assets/13770771/19008017/59445008-8736-11e6-93b4-a37c5ae68da5.png)

**Comment by koconnor719** [comment]
will the first box (total searches) auto update?  or will ad hoc analytics person update manually?

**Comment by robertfairhead** [comment]
Fixed sizing per #74 unless you make further changes to them.

First and third boxes will be manual updates. It takes about 10 minutes once per month to update. Can be automated but low priority given low effort required at this point.

**Comment by robertfairhead** [comment]
Updated with September data.
