### ISSUE TITLE
education application quote

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#81]
heres' the quote for this metric:

Veteran User 1:  [on old system]  It was a lot more writing. Everything was... not put together, but it was close together. So it was kind of jumbled up.   [on vets.gov] This is very spread out, which I like. I like that. There is no confusion.

Veteran User 2: [vets.gov] It’s really simple. It’s like, [barney] proof. Military people love that. They love that.

![screen shot 2016-09-30 at 5 58 41 pm](https://cloud.githubusercontent.com/assets/13770771/19008211/8bd710d6-8737-11e6-9c52-d3dd991b92bf.png)

**Comment by robertfairhead** [comment]
Added the quote tile here and both onto the veteran research page per #64
