### ISSUE TITLE
claim status after screenshot

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#82]
@suzchap is there a  more recent screenshot we can include with the language on the phases modified; i know these are in process:) ?

if you or mel can post something on Monday by COB we can add it to the scorecard:)  

![screen shot 2016-09-30 at 6 03 28 pm](https://cloud.githubusercontent.com/assets/13770771/19008288/36512bb4-8738-11e6-8d72-723385f26145.png)

**Comment by suzchap** [comment]
![desktop-status](https://cloud.githubusercontent.com/assets/11219417/19039622/b9ba20a6-894e-11e6-9a4f-c2fa9ed0a043.png)

**Comment by robertfairhead** [comment]
Updated after screenshot
