### ISSUE TITLE
claim status metric site reliability

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#83]
so good news and bad:  we have a before metric--but i think it's just too low to even use:  76% availability. bad news is this will constrain us--so we can't say 99.99% here.

let's just say "improved availability" and have an icon??  if you have better ideas let me know:)

keep in mind this may get forwarded externally so we want to be conscious of that.  accurate but i don't want to throw a team under the bus.

**Comment by robertfairhead** [comment]
Added a general improved reliability tile.
