### ISSUE TITLE
veteran employment center card change (front and back)

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#85]
let's change front card sentence to,  "Saved VA $14M+ in vendor estimated costs by delivering the product for just $9K (in two (2) weeks) that consolidated 40 Veteran employment sites.

and all 3 metrics please per marina's wealth of info!!

1 Cost Savings :   "Vendor cost estimate" $14M / vets.gov actual launch cost $9K

2. TCO (total cost of ownership) savings:  "Vendor charge to VA to change a single link: $100K" / vets.gov cost to change a link $0
 
3.  Delivery Speed: "Vendor estimate to launch: 2 years / vets.gov actual delivery: 1 month"  change graph from 1 year to 2!!

![screen shot 2016-09-30 at 6 56 14 pm](https://cloud.githubusercontent.com/assets/13770771/19009227/9720e126-873f-11e6-8a40-b3d168eba9a4.png)

**Comment by koconnor719** [comment]
change the front card sentence to: "Saved VA $14M"

**Comment by koconnor719** [comment]
this card might be my favorite.

**Comment by robertfairhead** [comment]
Updated the text on front/back of card. I had to trim it down a bit to fit on front of card. Updated all featured metric tiles.

**Comment by koconnor719** [comment]
looks good!
