### ISSUE TITLE
secure message before and after

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/vets.gov-status#88]
@angel can you get @robertfairhead   some good "before " and "after" screenshot for SM on Monday if you have time?  they don't have to be final:) 

pls. pick the worst before possible:)  thanks.  this is for our scorecard fyi.  https://adhocteam.github.io/vets.gov-status/boards/securemessaging.html

@ayaleloehr fyi; no action unless you have any other metrics you want to highlight

**Comment by angel** [comment]
@koconnor719 

### Inbox: 
Before:
![secure messaging - inbox](https://cloud.githubusercontent.com/assets/103496/19051966/dc72f9c2-8969-11e6-8c45-e74d17769fb5.png)
After:
![inbox](https://cloud.githubusercontent.com/assets/103496/19051997/e96f1db8-8969-11e6-8f66-021482a2d2c3.png)

### New message:
Before:
![secure messaging - new message](https://cloud.githubusercontent.com/assets/103496/19052233/e34c9efa-896a-11e6-9b1b-1652fd2dfd53.png)
After:
![new message](https://cloud.githubusercontent.com/assets/103496/19052189/b368c8f8-896a-11e6-9d95-443fe4a537db.png)

### View message:
Before:
![secure messaging - read meesage with next message](https://cloud.githubusercontent.com/assets/103496/19052364/5681701c-896b-11e6-8355-c6e17532169e.png)
After:
![view message - thread and attachment expanded](https://cloud.githubusercontent.com/assets/103496/19052340/3b7e4b96-896b-11e6-8a66-78acfba36403.png)

**Comment by koconnor719** [comment]
thx @angel !!

**Comment by robertfairhead** [comment]
Added before/after screenshots. Used the message detail view.
